# Generated by Django 2.0.6 on 2018-07-01 08:18

from django.db import migrations, models
import zds_schema.validators


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_auto_20180701_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enkelvoudiginformatieobject',
            name='bronorganisatie',
            field=models.CharField(blank=True, default='', help_text='Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die het informatieobject heeft gecreëerd of heeft ontvangen en als eerste in een samenwerkingsketen heeft vastgelegd.', max_length=9, validators=[zds_schema.validators.validate_non_negative_string]),
            preserve_default=False,
        ),
    ]
