# Generated by Django 2.0.6 on 2018-07-30 13:17

from django.db import migrations
import zds_schema.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0008_auto_20180730_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='enkelvoudiginformatieobject',
            name='vertrouwelijkheidsaanduiding',
            field=zds_schema.fields.VertrouwelijkheidsAanduidingField(blank=True, choices=[('openbaar', 'OPENBAAR'), ('beperkt openbaar', 'BEPERKT OPENBAAR'), ('intern', 'INTERN'), ('zaakvertrouwelijk', 'ZAAKVERTROUWELIJK'), ('vertrouwelijk', 'VERTROUWELIJK'), ('confidentieel', 'CONFIDENTIEEL'), ('geheim', 'GEHEIM'), ('zeer geheim', 'ZEER GEHEIM')], help_text='Aanduiding van de mate waarin het INFORMATIEOBJECT voor de openbaarheid bestemd is.', max_length=20),
        ),
    ]
