# Generated by Django 2.0.6 on 2018-08-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0010_auto_20180815_1104"),
        ("datamodel", "0010_auto_20180815_1221"),
    ]

    operations = []
