# Generated by Django 2.0.6 on 2018-09-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0015_remove_objectinformatieobject_zaak")]

    operations = [
        migrations.AlterUniqueTogether(
            name="objectinformatieobject",
            unique_together={("informatieobject", "object")},
        )
    ]
