# Generated by Django 2.0.9 on 2018-12-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0027_auto_20181219_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='enkelvoudiginformatieobject',
            name='status',
            field=models.CharField(blank=True, choices=[('in bewerking', 'Aan het informatieobject wordt nog gewerkt.'), ('ter vaststelling', 'Informatieobject gereed maar moet nog vastgesteld worden.'), ('definitief', 'Informatieobject door bevoegd iets of iemand vastgesteld dan wel ontvangen.'), ('gearchiveerd', 'Informatieobject duurzaam bewaarbaar gemaakt; een gearchiveerd informatie-element.')], help_text="Aanduiding van de stand van zaken van een INFORMATIEOBJECT. De waarden 'in bewerking' en 'ter vaststelling' komen niet voor als het attribuut `ontvangstdatum` van een waarde is voorzien.", max_length=20, verbose_name='status'),
        ),
    ]
