# Generated by Django 2.0.9 on 2018-12-24 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0030_gebruiksrechten'),
    ]

    operations = [
        migrations.AddField(
            model_name='gebruiksrechten',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True),
        ),
    ]
