# Generated by Django 2.0.10 on 2019-03-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0032_auto_20190129_1031")]

    operations = [
        migrations.RenameField(
            model_name="enkelvoudiginformatieobject",
            old_name="vertrouwelijkaanduiding",
            new_name="vertrouwelijkheidaanduiding",
        )
    ]
