# Generated by Django 2.0.13 on 2019-05-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0033_auto_20190301_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectinformatieobject',
            options={'verbose_name': 'Objectinformatieobject', 'verbose_name_plural': 'Objectinformatieobjecten'},
        ),
        migrations.RemoveField(
            model_name='objectinformatieobject',
            name='aard_relatie',
        ),
        migrations.RemoveField(
            model_name='objectinformatieobject',
            name='beschrijving',
        ),
        migrations.RemoveField(
            model_name='objectinformatieobject',
            name='registratiedatum',
        ),
        migrations.RemoveField(
            model_name='objectinformatieobject',
            name='titel',
        ),
        migrations.AlterUniqueTogether(
            name='enkelvoudiginformatieobject',
            unique_together={('bronorganisatie', 'identificatie')},
        ),
    ]
