# Generated by Django 2.0.13 on 2019-05-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0033_auto_20190301_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='enkelvoudiginformatieobject',
            name='lock',
            field=models.CharField(blank=True, default='', help_text='Hash string, which represents id of the lock', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='enkelvoudiginformatieobject',
            unique_together={('bronorganisatie', 'identificatie')},
        ),
    ]
