# Generated by Django 2.0.13 on 2019-06-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0034_auto_20190528_0927'),
        ('datamodel', '0034_auto_20190524_1455'),
    ]

    operations = [
    ]
