# Generated by Django 2.2.2 on 2019-06-14 08:34

from django.db import migrations


def create_canonicals(apps, schema_editor):
    EnkelvoudigInformatieObject = apps.get_model('datamodel', 'EnkelvoudigInformatieObject')
    EnkelvoudigInformatieObjectCanonical = apps.get_model('datamodel', 'EnkelvoudigInformatieObjectCanonical')
    for eio in EnkelvoudigInformatieObject.objects.all():
        canonical = EnkelvoudigInformatieObjectCanonical.objects.create(id=eio.id)
        eio.canonical = canonical
        eio.save()

        eio.gebruiksrechten_set.update(canonical=canonical)
        eio.objectinformatieobject_set.update(canonical=canonical)


def remove_canonicals(apps, schema_editor):
    EnkelvoudigInformatieObjectCanonical = apps.get_model('datamodel', 'EnkelvoudigInformatieObjectCanonical')
    for eio_canonical in EnkelvoudigInformatieObjectCanonical.objects.all():
        related_eios = eio_canonical.enkelvoudiginformatieobject_set.all().order_by('-versie')
        latest = related_eios.first()
        for eio in related_eios:
            eio.canonical = None
            eio.save()

        for gebruiksrechten in eio_canonical.gebruiksrechten_set.all():
            gebruiksrechten.canonical = None
            gebruiksrechten.informatieobject = latest
            gebruiksrechten.save()

        for objectinformatieobject in eio_canonical.objectinformatieobject_set.all():
            objectinformatieobject.canonical = None
            objectinformatieobject.informatieobject = latest
            objectinformatieobject.save()


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0037_auto_20190614_0834'),
    ]

    operations = [
        migrations.RunPython(create_canonicals, remove_canonicals)
    ]
