# Generated by Django 2.2.2 on 2019-06-14 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0038_auto_20190614_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gebruiksrechten',
            name='canonical',
        ),
        migrations.RemoveField(
            model_name='objectinformatieobject',
            name='canonical',
        ),
        migrations.AlterField(
            model_name='enkelvoudiginformatieobject',
            name='canonical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.EnkelvoudigInformatieObjectCanonical'),
        ),
        migrations.AlterField(
            model_name='gebruiksrechten',
            name='informatieobject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.EnkelvoudigInformatieObjectCanonical'),
        ),
        migrations.AlterField(
            model_name='objectinformatieobject',
            name='informatieobject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.EnkelvoudigInformatieObjectCanonical'),
        ),
    ]
