# Generated by Django 2.2.2 on 2019-07-04 15:11

from django.db import migrations, models
import django.db.models.deletion
import privates.fields
import privates.storages
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0041_migrate_to_flattened_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='enkelvoudiginformatieobject',
            name='bestandsomvang',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PartUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('part_number', models.PositiveIntegerField(help_text='A sequence number of file part within document')),
                ('chunk_size', models.PositiveIntegerField(help_text='The size of a chunk in bytes')),
                ('inhoud', privates.fields.PrivateMediaFileField(null=True, storage=privates.storages.PrivateMediaFileSystemStorage(), upload_to='uploads/%Y/%m/')),
                ('informatieobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='datamodel.EnkelvoudigInformatieObjectCanonical')),
            ],
            options={
                'unique_together': {('informatieobject', 'part_number')},
            },
        ),
    ]
