# Generated by Django 2.2.2 on 2019-07-01 15:28

from django.db import migrations


def rewrite_file_size(apps, schema_editor):
    EnkelvoudigInformatieObject = apps.get_model("datamodel.EnkelvoudigInformatieObject")

    docs = EnkelvoudigInformatieObject.objects.all()
    for doc in docs:
        doc.bestandsomvang = doc.inhoud.size
        doc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0042_auto_20190704_1511'),
    ]

    operations = [
        migrations.RunPython(rewrite_file_size, migrations.RunPython.noop),
    ]
