# Generated by Django 2.2.2 on 2019-07-05 08:17

from django.db import migrations, models
import django.db.models.deletion
import privates.fields
import privates.storages
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0046_auto_20190716_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='enkelvoudiginformatieobject',
            name='bestandsomvang',
            field=models.PositiveIntegerField(default=0, help_text='The size of the whole file in bytes', verbose_name='bestandsnaam'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BestandsDeel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('index', models.PositiveIntegerField(help_text='Een volgnummer dat de volgorde van de bestandsdelen aangeeft.')),
                ('grootte', models.PositiveIntegerField(help_text='De grootte van dit specifieke bestandsdeel.')),
                ('inhoud', privates.fields.PrivateMediaFileField(blank=True, storage=privates.storages.PrivateMediaFileSystemStorage(), upload_to='part-uploads/%Y/%m/', help_text="De (binaire) bestandsinhoud van dit specifieke bestandsdeel.")),
                ('informatieobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestandsdelen', to='datamodel.EnkelvoudigInformatieObjectCanonical')),
            ],
            options={
                'unique_together': {('informatieobject', 'index')},
            },
        ),
    ]
