# Generated by Django 2.2.4 on 2020-10-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0046_auto_20190716_1513"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectinformatieobject",
            name="object",
            field=models.URLField(
                help_text="URL-referentie naar het gerelateerde OBJECT (in deze of een andere API).",
                max_length=1000,
            ),
        ),
    ]
