# Generated by Django 2.2.4 on 2019-10-09 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0051_auto_20190910_1318")]

    operations = [
        migrations.AlterField(
            model_name="bestandsdeel",
            name="omvang",
            field=models.BigIntegerField(
                help_text="De grootte van dit specifieke bestandsdeel.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="enkelvoudiginformatieobject",
            name="bestandsomvang",
            field=models.BigIntegerField(
                help_text="Aantal bytes dat de inhoud van INFORMATIEOBJECT in beslag neemt.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="bestandsomvang",
            ),
        ),
    ]
