# Generated by Django 2.2.4 on 2019-11-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0052_auto_20191009_0904"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectinformatieobject",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("besluit", "Besluit"),
                    ("zaak", "Zaak"),
                    ("verzoek", "Verzoek"),
                ],
                help_text="Het type van het gerelateerde OBJECT.",
                max_length=100,
                verbose_name="objecttype",
            ),
        ),
    ]
