# Generated by Django 2.2.4 on 2022-01-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0055_verzending"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verzending",
            options={
                "verbose_name": "Verzending",
                "verbose_name_plural": "Verzendingen",
            },
        ),
    ]
