# Generated by Django 2.2.4 on 2022-02-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0055_verzending"),
    ]

    operations = [
        migrations.AddField(
            model_name="enkelvoudiginformatieobject",
            name="verschijningsvorm",
            field=models.TextField(
                blank=True,
                help_text="De essentiële opmaakaspecten van een INFORMATIEOBJECT.",
            ),
        ),
        migrations.AlterField(
            model_name="verzending",
            name="aard_relatie",
            field=models.CharField(
                choices=[("afzender", "Afzender"), ("geadresseerde", "Geadresseerde")],
                help_text="Omschrijving van de aard van de relatie van de BETROKKENE tot het INFORMATIEOBJECT.",
                max_length=255,
                verbose_name="aard relatie",
            ),
        ),
    ]
