# Generated by Django 2.2.4 on 2022-01-05 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0056_auto_20220105_1143"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verzending",
            name="binnenlands_correspondentieadres_huisnummer",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende nummering.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99999),
                ],
                verbose_name="huisnummer",
            ),
        ),
        migrations.AlterField(
            model_name="verzending",
            name="buitenlands_correspondentiepostadres_postbus_of_antwoord_nummer",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="De numerieke aanduiding zoals deze door de Nederlandse PTT is vastgesteld voor postbusadressen en antwoordnummeradressen.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="postbus-of antwoordnummer",
            ),
        ),
    ]
