# Generated by Django 3.2.13 on 2022-12-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0057_alter_enkelvoudiginformatieobject_indicatie_gebruiksrecht"),
    ]

    operations = [
        migrations.AddField(
            model_name="verzending",
            name="emailadres",
            field=models.CharField(
                blank=True,
                help_text="emailadres van de afzender.",
                max_length=100,
                verbose_name="emailadres",
            ),
        ),
        migrations.AddField(
            model_name="verzending",
            name="faxnummer",
            field=models.CharField(
                blank=True,
                help_text="Faxnummer van de afzender.",
                max_length=15,
                verbose_name="faxnummer",
            ),
        ),
        migrations.AddField(
            model_name="verzending",
            name="mijn_overheid",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="mijnOverheid van de afzender.",
                verbose_name="mijn overheid",
            ),
        ),
    ]
