# Generated by Django 2.2.4 on 2022-01-05 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0057_auto_20220105_1510"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verzending",
            name="buitenlands_correspondentiepostadres_postbus_of_antwoord_nummer",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="De numerieke aanduiding zoals deze door de Nederlandse PTT is vastgesteld voor postbusadressen en antwoordnummeradressen.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="postbus-of antwoordnummer",
            ),
        ),
    ]
