# Generated by Django 3.2.13 on 2022-12-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0058_auto_20221205_1053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verzending",
            name="emailadres",
            field=models.CharField(
                blank=True,
                help_text="emailadres van de afzender.",
                max_length=100,
                null=True,
                verbose_name="emailadres",
            ),
        ),
        migrations.AlterField(
            model_name="verzending",
            name="faxnummer",
            field=models.CharField(
                blank=True,
                help_text="Faxnummer van de afzender.",
                max_length=15,
                null=True,
                verbose_name="faxnummer",
            ),
        ),
    ]
