# Generated by Django 3.2.13 on 2023-02-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0060_auto_20230119_0838"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verzending",
            name="telefoonnummer",
            field=models.CharField(
                blank=True,
                help_text="telefoonnummer van de afzender.",
                max_length=15,
                null=True,
                verbose_name="telefoonnummer",
            ),
        ),
    ]
