# Generated by Django 3.2.13 on 2023-02-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0061_alter_verzending_telefoonnummer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verzending",
            name="emailadres",
            field=models.CharField(
                blank=True,
                help_text="emailadres van de ontvanger of afzender.",
                max_length=100,
                null=True,
                verbose_name="emailadres",
            ),
        ),
        migrations.AlterField(
            model_name="verzending",
            name="faxnummer",
            field=models.CharField(
                blank=True,
                help_text="faxnummer van de ontvanger of afzender.",
                max_length=15,
                null=True,
                verbose_name="faxnummer",
            ),
        ),
        migrations.AlterField(
            model_name="verzending",
            name="mijn_overheid",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="is het informatieobject verzonden via mijnOverheid naar de ontvanger.",
                verbose_name="mijn overheid",
            ),
        ),
        migrations.AlterField(
            model_name="verzending",
            name="telefoonnummer",
            field=models.CharField(
                blank=True,
                help_text="telefoonnummer van de ontvanger of afzender.",
                max_length=15,
                null=True,
                verbose_name="telefoonnummer",
            ),
        ),
    ]
