# Generated by Django 3.2.13 on 2023-04-19 12:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0062_auto_20230222_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='enkelvoudiginformatieobject',
            name='trefwoorden',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text="Een lijst van trefwoorden gescheiden door comma's.", null=True, size=None),
        ),
    ]
