# Generated by Django 3.2.13 on 2023-10-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0064_bestandsdeel_lock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bestandsdeel",
            name="lock",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hash string, which represents id of the lock",
                max_length=100,
            ),
        ),
    ]
