# Generated by Django 3.2.13 on 2024-03-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0065_auto_20231204_1305"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enkelvoudiginformatieobject",
            name="archiefstatus",
        ),
        migrations.RemoveField(
            model_name="enkelvoudiginformatieobject",
            name="bevat_persoonsgegevens",
        ),
        migrations.RemoveField(
            model_name="enkelvoudiginformatieobject",
            name="ontvangen",
        ),
        migrations.RemoveField(
            model_name="enkelvoudiginformatieobject",
            name="vervallen",
        ),
        migrations.AddField(
            model_name="enkelvoudiginformatieobject",
            name="inhoud_is_vervallen",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Geeft aan of de inhoud van het informatieobject vervallen (dus niet langer geldig) is.",
                null=True,
                verbose_name="inhoud is vervallen",
            ),
        ),
        migrations.AlterField(
            model_name="bestandsdeel",
            name="lock",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hash string, which represents id of the lock",
                max_length=100,
            ),
        ),
    ]
