# Generated by Django 3.2.13 on 2023-12-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0065_alter_bestandsdeel_lock"),
    ]

    operations = [
        migrations.AddField(
            model_name="enkelvoudiginformatieobject",
            name="archiefstatus",
            field=models.CharField(
                choices=[
                    (
                        "nog_te_archiveren",
                        "De zaak cq. het zaakdossier is nog niet als geheel gearchiveerd.",
                    ),
                    (
                        "gearchiveerd",
                        "De zaak cq. het zaakdossier is als geheel niet-wijzigbaar bewaarbaar gemaakt.",
                    ),
                ],
                default="nog_te_archiveren",
                help_text="Aanduiding of het zaakdossier blijvend bewaard of na een bepaalde termijn vernietigd moet worden.",
                max_length=40,
                verbose_name="archiefstatus",
            ),
        ),
        migrations.AddField(
            model_name="enkelvoudiginformatieobject",
            name="bevat_persoonsgegevens",
            field=models.CharField(
                choices=[
                    (
                        "onbekend",
                        "Niet bekend of het document persoonsgegevens bevat dieniet vrijelijk openbaar gemaakt mogen worden.",
                    ),
                    (
                        "ja",
                        "Niet bekend of het document persoonsgegevens bevat dieniet vrijelijk openbaar gemaakt mogen worden.",
                    ),
                    (
                        "nee",
                        "Bevat geen persoonsgegevens die niet vrijelijk openbaargemaakt mogen worden.",
                    ),
                ],
                default="onbekend",
                help_text="Legt vast of het document persoonsgegevens bevat die niet vrijelijk openbaar gemaakt mogen worden.",
                max_length=40,
                null=True,
                verbose_name="bevat persoonsgegevens",
            ),
        ),
        migrations.AddField(
            model_name="enkelvoudiginformatieobject",
            name="ontvangen",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Legt vast of het document afkomstig is van een externe partij.",
                null=True,
                verbose_name="ontvangen",
            ),
        ),
        migrations.AddField(
            model_name="enkelvoudiginformatieobject",
            name="vervallen",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Legt vast of het document een rol speelt in het huidige of toekomstige proces.",
                null=True,
                verbose_name="vervallen",
            ),
        ),
        migrations.AlterField(
            model_name="enkelvoudiginformatieobject",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("in_bewerking", "In bewerking"),
                    ("concept", "Concept"),
                    ("definitief", "Definitief"),
                    ("ter_vaststelling", "Ter vaststelling"),
                    ("vastgesteld", "Vastgesteld"),
                    ("gearchiveerd", "Gearchiveerd"),
                ],
                help_text="Aanduiding van de stand van zaken van een INFORMATIEOBJECT. De waarden 'in bewerking' en 'ter vaststelling' komen niet voor als het attribuut `ontvangstdatum` van een waarde is voorzien. Wijziging van de Status in 'gearchiveerd' impliceert dat het informatieobject een duurzaam, niet-wijzigbaar Formaat dient te hebben.",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
