name: Code quality checks

on:
  push:
    branches:
      - "master"
      - "stable/*"
  pull_request:

jobs:
  isort:
    name: Code imports
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements/ci.txt
      - name: Run isort
        run: isort --check-only --diff .

  black:
    name: Code format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements/ci.txt
      - name: Run black
        run: black --check --diff src docs
